### ISSUE TITLE
Assignment 1 [Azin Karimzad]

### ISSUE THREAD

**Issue by Azinkarimzad** [EstherPlomp/TNW-RDM-101#14]
### Introduction
<Hi Everyone, My name is Azin. I am a PhD candidate in geophysics group- Imaging physics.>

### Reflections on the importance of RDM videos
<I like the idea of knowing that my problem with data management is something that many people struggle with. It helps me to look for solutions that others have found to overcome these issues. Although I don't have any interesting horror stories related to data management, I have noticed that when my data is in a more reliable and reproducible form, I am able to publish better outcomes!>

### What would you like to learn during this course? 
<I do always struggle with remembering where I have stored my data, and codes, Which one is the last version, or naming them wisely and get rid of "finalfinallast2" versions!!>

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/7)'
- [x] Assignment 2: Data Flow Map 1 (share a link in this issue before **7 March 13:00**)
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/10)'
- [x] Respond to **[this](https://surfdrive.surf.nl/files/index.php/s/r1gn485T0rE0g7a)** GitHub issue with your readme file
- [x] Assignment 3: Data Flow Map 2 (share a link in this issue before **14 March 13:00**)
- [ [link](https://surfdrive.surf.nl/files/index.php/s/GhEhRf6awIfaYEr)]
- [x] Assignment 4: Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/11)' if you have any questions (optional)
- [x] Assignment 5: Data Flow Map 3: submit [your](https://surfdrive.surf.nl/files/index.php/s/QUWX9YoR3R9NZgL) slide (before **Class 2**)

**Comment by Azinkarimzad** [comment]
Link to 2nd assignment:

**Comment by RamonvanValderen** [comment]
Hi Azin, unfortunately I am unable to access your data flow map as I am not authorized to access your Surfdrive.

**Comment by EstherPlomp** [comment]
Same! Can you try to generate a public sharing link? If the information in [SURFdrive sharing](https://estherplomp.github.io/TNW-OS-support/posts/data-sharing-SURFdrive) is not clear, please let me know!

**Comment by EstherPlomp** [comment]
Also: on your question for training also accessible to partners outside of the university. I asked around and came up with the following options: 
- Code Refinery. Their [next workshop is in March](https://coderefinery.github.io/2023-03-21-workshop/). I think they still take sign-ups and otherwise there is also a [recording available from a previous workshop](https://www.youtube.com/watch?v=GHlF1nGfz7g&list=PLpLblYHCzJACqaFsfQiCWp0Wqy6qG4iau), and all the [materials are also available online](https://coderefinery.org/lessons/core/). 
- Carpentries Workshops. These are more beginnerish and may not always focus on just GitHub or collaborative coding. Lessons that would be relevant are: https://swcarpentry.github.io/git-novice/ (modules 7-9 most relevant to your question). They have a [list of upcoming workshops on their website ](https://software-carpentry.org/)- most of those are free to join for anyone but some might have specific restrictions. 

Hope this helps!

**Comment by EstherPlomp** [comment]
Thanks @Azinkarimzad! 

Just a couple of questions/suggestions: 
- I see you got a 'personal data' flag: do you really collect/process data that can lead to the identification of a person in your geological models? Alternatively, if you're reliant on collaborators (sister projects), this could be tagged as a red flag because you're dependent on your collaborators for data access and use. 
- Just a note on the use of GitLab/GitHub: if Delfi is having their own instance it will be a safer solution for confidential data. [TU Delft also has a GitLab instance.](https://gitlab.tudelft.nl) There is nothing wrong with GitHub, but even private repositories are accessible by the platform's owner - microsoft - and you may not have full control over what they do with things on their platform. This can be a problem for confidential data. 
- What is your supervisor's private storage space? And what is your place to store data? GitLab/Hub is not ideal for large files: do you have enough space available with the storage solutions that you're using?

**Comment by Azinkarimzad** [comment]
@EstherPlomp
Thanks for the feedback! 1) I think I may have mistaken the concept of "personal data." I meant more of a confidential dataset, so I will change the flag accordingly.

That's a great point. I will store the scripts on TU-Delft GitLab as well.
By "private storage," I meant an external HDD. I have stored my data on Google Drive and SurfDrive, but I will make it clear in the data management plan.

**Comment by Azinkarimzad** [comment]
Edited data_managment
--
https://surfdrive.surf.nl/files/index.php/s/hN5hkqEtBhmz3Sj

**Comment by sweerdenburg1** [comment]
> Link to 2nd assignment: https://surfdrive.surf.nl/files/index.php/f/12672995699

Hi Azin, I do not have permission to 

> > Hi Azin, unfortunately I am unable to access your data flow map as I am not authorized to access your Surfdrive.
> 
> Hi, I just corrected the link. https://surfdrive.surf.nl/files/index.php/s/BHneZ0rai7PEgIF

Hi Azin, your data flow map looks good! Looks like you've got some red flags that may influence the sharing and storing of your data. I was wondering whether the geo models and scripts considered as personal data because they contain personal information, but I see that Esther has commented on this already.

**Comment by bertvanherck** [comment]
Hi Azin, nice data flow map. Looks clear to me. Maybe one remark (because of a personal experience): if data, scripts, ... are stored on drives that belong to other persons, make sure you have a copy of everything before they leave. So, you are sure you do not loose data (or time asking your data back).

**Comment by Azinkarimzad** [comment]
> Also: on your question for training also accessible to partners outside of the university. I asked around and came up with the following options:
> 
> * Code Refinery. Their [next workshop is in March](https://coderefinery.github.io/2023-03-21-workshop/). I think they still take sign-ups and otherwise there is also a [recording available from a previous workshop](https://www.youtube.com/watch?v=GHlF1nGfz7g&list=PLpLblYHCzJACqaFsfQiCWp0Wqy6qG4iau), and all the [materials are also available online](https://coderefinery.org/lessons/core/).
> * Carpentries Workshops. These are more beginnerish and may not always focus on just GitHub or collaborative coding. Lessons that would be relevant are: https://swcarpentry.github.io/git-novice/ (modules 7-9 most relevant to your question). They have a [list of upcoming workshops on their website ](https://software-carpentry.org/)- most of those are free to join for anyone but some might have specific restrictions.
> 
> Hope this helps!

Thanks Esther. I just registered in the code-refinery as well.

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 - and for updating the personal data flag with the confidential one!

Small note on your first slide on data organisation: 
- If you add the date in front of the file name things will automatically be chronologically ordered. I personally like to organise things like this, but your file naming also looks good: I think this is more of a personal preference thing. 
- And a repeat of the question I also put in the discussion thread: Will you have separate directories/folders for each of your manuscript chapters/articles?

On documentation: 
- I like your powerpoint file approach: sometimes the more 'rudimentary' approaches just work best! Especially if this already helps you with figures in the long run! (Also: I know that groups at Quantum Nanoscience also work with a similar approach - so it might be more common than you think!)
- Regarding your phrase _'the use of persistent identifiers is of great importance in this context to refer to each file.'_ Do you mean that you will upload multiple files separately to a public repository that each need a persistent identifier (such as a DOI)? Or do you mean that each file needs a unique identifier so that you're able to distinguish them? I think the latter? 
- If you're working with a lot of scripts, Jupyter notebooks and GitBook are indeed nice ways to organise documentation!

On metadata:
- Does it also make sense to include information about when you generated the model? Is this already automatically done?
- For scripts, maybe also include dependencies and/or libraries used

On Access: 
- If you work with confidential data and you need restricted access for this, GitLab is the safest solution to share scripts. GitHub is owned by Microsoft and even when you have a private repository - Microsoft could still access it. The same applies to google drive storage locations: unless you have a paid license you automatically give Google rights to everything that you share with them. 
- Will you be able to share the data/code underlying your thesis chapters/articles? Or is this also not possible? 

On Data publication: 
- If you are able to share (some of the) scripts publicly, GitHub is a great solution indeed. Especially if you expect others to build on things or collaborate with others! GitHub does not assign DOIs to the repositories though, so for that you can share a snapshot of your repository via Zenodo (see [here for more information](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content)) or 4TU.ResearchData (the repository will be updated so this process might change before you need to make use of it - please get in touch when you want to share the code so that I can provide you with updated info!). 
- You can use AWS (although for confidential data please check if it is allowed to use this storage solution because this is managed by Amazon - or the Project Drive. Ideally you can share most of your data/scripts publicly so that it can be on a data repository such as Zenodo or 4TU.ResearchData. This way it is also easier for yourself to reuse the work when you leave the university.
- For more information on software licenses, see the [resources in the course materials](https://estherplomp.github.io/TNW-RDM-101/07-FAIR-principles.html#data-and-code-licences).

I hope this helps! If I made anything more unclear, please let me know!

**Comment by EstherPlomp** [comment]
Hi @Azinkarimzad! 

Thanks for sharing your READme file! Did you find it difficult to set up a READme file? What would help with this assignment? 

Also a comment on ORCIDs: these are identifiers for researchers. You can [set up your own ORCID](https://orcid.org/) and use it to maintain an overview of your research outputs and presentations. See [my ORCID](https://orcid.org/0000-0003-3625-1357) as an example of how a filled out profile could look like.
