### ISSUE TITLE
Assignment 1 Beatriz Diniz

### ISSUE THREAD

**Issue by MBeatrizDiniz** [EstherPlomp/TNW-RDM-101#16]
### Introduction

Hello, my name is Beatriz I am a PhD student from the Environmental Biotechnology department. In my free time I love to read and bake.

### Reflections on the importance of RDM videos

The accessibility and reproducibility of your data give continuity to your research after you.

### What would you like to learn during this course? 

Tools that make data accessible and how to ensure continuity between master student projects. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/7)'
- [x] Assignment 2: Data Flow Map 1 (share a link in this issue before **7 March 13:00**)
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/10)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Assignment 3: Data Flow Map 2 (share a link in this issue before **14 March 13:00**)
- [x] Assignment 4: Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/11)' if you have any questions (optional)
- [x] Assignment 5: Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by MBeatrizDiniz** [comment]
**Assignment 2:** 

https://tud365-my.sharepoint.com/:p:/g/personal/mcanongialopes_tudelft_nl/EQDw9O-sjgJEpPZ3pBL3MycBQVeWFFsDwLgw8szdxRNe_w?e=ZdMNlv

**Comment by TamaraJankovic03** [comment]
Hi Beatriz,

I really like your Data Flow Map, especially since you have a clear vision of how student projects can be incorporated into your project. I am also storing my data on the project and the group drive. Additionally, I am making a back-up of my data on an external hard drive.

**Comment by EstherPlomp** [comment]
Hi @MBeatrizDiniz!  
- I agree with @TamaraJankovic03's comment on the student projects! You could also add a red flag there, not because the students are a 'red flag', but because you do have to work together on things - so it can be an added complication in that sense.  
- You haven't added the file formats of the data yet - this becomes more important for assignment 3. Good luck in the upcoming days!

**Comment by MBeatrizDiniz** [comment]
[readmefile -Beatriz Diniz.txt](https://github.com/EstherPlomp/TNW-RDM-101/files/10951053/readmefile.-Beatriz.Diniz.txt)

**Comment by MBeatrizDiniz** [comment]
**Assignment 3**

https://tud365-my.sharepoint.com/:p:/g/personal/mcanongialopes_tudelft_nl/EaoJXvNGB3ZApaScSlKF8WQBjPvywD6W1IR-KdGaBMB4Sg?e=gDMit4

**Comment by maverheijen** [comment]
Hi Bea,

Nice Data Flow Map, good that you included student projects! This is something I am now considering to add to my data flow map. You could elaborate on specific data maybe a bit more. In terms of data storage and back-ups we have very similar plans! :)

**Comment by EstherPlomp** [comment]
Well done on **assignment 3**!

On the theme Documentation (and Metadata): 
- You mention an excel template for data documentation: the columns of this template are also metadata!
- Is there any information/process on what happens if some of the values are missing in the excel template? (might not be applicable if you never have missing data)
- Are there any sub variables in the method/protocol information? (for example: temperature, time of experiment, amount of steps taken)

On file formats: 
- Very nice that you already start out with open file formats from the start! That makes sharing data/code in an open format later on much easier :) 

On data publication: 
- Which data repository to use is indeed a discussion to have with your supervisors! You'll also need this information for your Data Management Plan (Assignment 4). Let me know if you need more help or information on data repositories!

**Comment by TamaraJankovic03** [comment]
Hello @MBeatrizDiniz very organized README file! I think that you can add also the folder structure in DATA & FILE OVERVIEW to make it even more understandable for others. :)

**Comment by MBeatrizDiniz** [comment]
**Assignment 5**
https://tud365-my.sharepoint.com/:p:/g/personal/mcanongialopes_tudelft_nl/ERzYXJ1vTa9MqFuDxNugsmIBqW1LyXcVn3w7ACl01wmKRA?e=wYX4SQ

**Comment by EstherPlomp** [comment]
Thanks for your slide @MBeatrizDiniz! 

Fair point on the file formats 👍 I'm happy to see that the readme files are useful!

**Comment by EstherPlomp** [comment]
Hi @MBeatrizDiniz: thanks for sharing your READme file. As @TamaraJankovic03 already mentioned - this looks very clear and organised, well done!

I see you're not referring to an ORCID, so I just wanted to point out that this is an identifier for researchers. Similar like the identifier to the publication, it provides a way to easily identify you as a person and associate your research outputs with you. You can [set up your own ORCID](https://orcid.org/register) very easily (and use it for some scholarly platforms such as Zenodo/publishing platforms). You can have a look at [my ORCID](https://orcid.org/0000-0003-3625-1357) to see what it looks like when there is information in the profile.
