### ISSUE TITLE
Data Challenge

### ISSUE THREAD

**Issue by EstherPlomp** [EstherPlomp/TNW-RDM-101#2]
What is your main challenge regarding your data management? Please respond below with your data challenge! 

Please read your peers’ responses and reply to any you find interesting.

**Comment by mausi122** [comment]
Creating a properly backed up and version controlled measurement flow. (preferentially one that isn't too disruptive)
One of the big challenges is that during a measurement round we often change pieces of the code to optimise for that particular sample, this is ad hoc and the changes that work for one sample might not work for the next one (or sometimes even the same one if it deteriorates with time).

**Comment by mausi122** [comment]
Creating a properly backed up and version controlled measurement flow. (preferentially one that isn't too disruptive)
One of the big challenges is that during a measurement round we often change pieces of the code to optimise for that particular sample, this is ad hoc and the changes that work for one sample might not work for the next one (or sometimes even the same one if it deteriorates with time). S

**Comment by JRdeJong** [comment]
During my research I will develop a lot of different scripts. Probably a lot of them will have only minor differences. The major challenge for me is to keep the different codes organized and to document the different codes in a descriptive way.

**Comment by bauerjana** [comment]
Since we started with a new branch in our lab, we need to set up a lot of things from scratch: new CAD workflows to design our samples, new fabrication recipes in the cleanroom, new measurement flows to characterize samples for the further examination, new code to carry out the device characterization as well as the actual measurements of particular samples afterwards, new code to analyze the data and new ways to present our findings. We can build upon already existing structures, but will need to modify and add a lot of steps. The challenge will also be to have a suitable version control, since CADs/recipes/code/etc are still under development and change massively.

**Comment by Nasimhd** [comment]
> During my research I will develop a lot of different scripts. Probably a lot of them will have only minor differences. The major challenge for me is to keep the different codes organized and to document the different codes in a descriptive way.

This is my issue, too. I still have not found a good approach to save my codes such that I can easily find the one I want later and know what changes I made to it.

**Comment by AnaSacristan** [comment]
During my research I will take a lot of microscopy images and I will work with different analytical techniques for different samples. My biggest challenge is to organize all of the different results, maintain a structure and be able to keep track of them and localize them easily.
