### ISSUE TITLE
Assignment 1 Marit Verheijen

### ISSUE THREAD

**Issue by maverheijen** [EstherPlomp/TNW-RDM-101#21]
### Introduction

Hi, my name is Marit and I started as a PhD candidate in November at the Biotechnology department, specifically in the Environmental Biotechnology section. I love reading, climbing and playing field hockey in my free time :)

### Reflections on the importance of RDM videos

I have to say, I used to only consider RDM as a means to avoid losing your data - which would be a horror scenario for me. Luckily this hasn't happened so far. I either store things in the cloud, or I have at least one physical back-up on an external hard drive. For code, I have used Github for version control before, so I will also try to use this during my PhD. Although I always considered transparency/reproducibility as critical parts of science, I never realized that reproducibility was such a big part of (or better: reason for) RDM. I can see how solid data management also allows for critical and/or specific feedback on your results, analyses and code.

### What would you like to learn during this course? 

I always have back-ups of my work, often also in cloud storage to avoid issues with physical objects (computers/hard drives etc.) getting lost. However, I would like to improve on data storage in terms of organization and accessibility for others, specifically for supervision of students (long-term continuity) and the publication process.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/7)'
- [x] Assignment 2: Data Flow Map 1 (share a link in this issue before **7 March 13:00**)
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/10)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Assignment 3: Data Flow Map 2 (share a link in this issue before **14 March 13:00**)
- [x] Assignment 4: Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/11)' if you have any questions (optional)
- [x] Assignment 5: Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by maverheijen** [comment]
[RDM101_Assignment1_Week1_DataFlowMap_MaritVerheijen.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/10880248/RDM101_Assignment1_Week1_DataFlowMap_MaritVerheijen.pptx)

Assignment 2: Data Flow Map 1

**Comment by TamaraJankovic03** [comment]
Hi Marit,

I really like your Data Flow Map. :) I think that everything is clear and well-structured. I am also using the project data (:U) drive to store my data, in combination with copy on an external hard drive. I usually make a back-up of my data on this external drive at the end of each week, sometimes I do it even more often if I generate some very important data.

**Comment by EstherPlomp** [comment]
Hi @maverheijen! Well done on the extensive overview of the different types of data! A couple of things: 
- I see you're working with someone else / receiving data from collaborators. That could also be considered as a red flag (not because this is bad but you're dependent on other people for the data)
- I would consider working from OneDrive and then using Project Drive as a back up. That is in principle sufficient in terms of the 3-2-1 backup rule, but it never hurts to also back things up to an external harddrive! I tend to do this (bi)annually - or whenever one of the projects is finished and it makes sense to renew the backup to finalise the project. 
- You haven't added the file formats of the data yet - this becomes more important for assignment 3.

**Comment by MBeatrizDiniz** [comment]
Hello @maverheijen, very detailed research plan! I am also using both one drive and the Project drive. I also think the experimental output should have the same red flag as the experimental design.

**Comment by EstherPlomp** [comment]
Well done on assignment 3! 

On documentation: 
- Do you get all the documentation/information that you need from the sequencing/protein data? Any hurdles to expect later on when you need to describe the data in an article/chapter?

On file formats: 
- Since you haven't listed your file formats it is difficult for me to assess whether you are indeed working with open formats: are you working with csv / python files only? Or also other file formats? 
- I think sequencing data is generally shared in open/standard formats. When converting files to open formats always check if any information or functionalities are lost. Sometimes it is worthwhile to share both closed and open formats of the same file to keep the usability but also ensure the preservation of the files. 

On data publication: 
- Please have a look at the software licenses - CC BY-NC-SA 4.0 is not applicable for software. If you want a non commercial component in the license you may want to pay attention to the [copy left licenses](https://estherplomp.github.io/TNW-OS-support/posts/software-licenses/#restrictive-licences) (GPL3 is commonly used).

**Comment by TamaraJankovic03** [comment]
Hi @maverheijen very detailed and well-structured README file! I think that this data organization will make it easy for you and your collaborators to use the data. :)
