### ISSUE TITLE
Assignment 1 Annick Teepe

### ISSUE THREAD

**Issue by annickteepe** [EstherPlomp/TNW-RDM-101#23]
### Introduction

Hi everyone, my name is Annick Teepe. I'm a 2nd year PhD student at the department of quantum nanoscience. My research is about imaging spin waves in thin-film ferromagnets by making use of a sensor in diamond.

### Reflections on the importance of RDM videos

I agree that it is important to have a good method to save all research data. A couple of months ago when I came back from holidays the computer in the lab did not want to start anymore. I was afraid it was broken. Luckily all my data was backed up and notes synced online, so even if the PC had to be replaced i would not loose any data. I got the old pc to work in the end (:

### What would you like to learn during this course? 

Learn good practices regarding data management, especially on analysis. The raw data I have backed up, but my analysis scripts are a bit messy. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/7)'
- [x] Assignment 2: Data Flow Map 1, here is the [link](https://tud365-my.sharepoint.com/:p:/g/personal/annickteepe_tudelft_nl/EZZi9mBO1zpAtgG2mxaxDm0BGuM3lsewvcFuEu88DDgOJQ?e=NpGOpV)
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/10)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Assignment 3: Data Flow Map 2 , here is the [link](https://tud365-my.sharepoint.com/:p:/g/personal/annickteepe_tudelft_nl/EeIPfm2edCZFhGw8OuZl3mABpRwZ1k-OOMlm055M-ODE4A?e=3KEWz5)
- [x] Assignment 4: Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/11)' if you have any questions (optional)
- [x] Assignment 5: Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by MpaulaL** [comment]
Hi Annick (@annickteepe), my name is Paula and I am the instructor supporting Esther in this run of the course. I normally teach in the RDM101 course we provide centrally at the library for all the faculties.
Thank you very much for submitting your assignment and for your reflection on storage and back-up. I would like to share some comments/suggestions/questions which I hope help them with working on your RDM strategy :-)
My first question would be, what is NAVFM? :-P
It is a good list of data types and code! But, for the purpose of the assignment and also to help improving your RDM strategy maybe it would be good to have a bit more detailed list. For example, the raw measurement data, it would be good to know how do you collect those data. You mention that they come from the NAVFM GUIs, but are they collected with instruments? Which instruments? Are these GUIs different software associated to the instruments? Are these proprietary software or software develop by your group? Have a bit more thorough description can help to decide later on how to organize these data, which data you will need to publish or preserve for re-usability, which type of documentation needs to accompany these data, etc. The same for the code, I would split one category call Measurement scripts and another analysis scripts, for example.
Also, the category called 'measurement data specific experiments' I read is a combination of raw data and maybe intermediate or analyzed data? Did you decided to group because that is the way you store them? When you explore the chapter on data organization, you will learn that it is a good practice to split data from code, but also split raw data from intermediate/analyzed data. So, I would suggest not to think about the data on how your are storing/organizing it, but identify the different types or stages of data according to your workflow. It would be great if you could do those changes before working on the next assignment, it will make it easier for the reflection on the themes that are coming up.
About storage. I see that the data is collected automatically in some folders, which is great to have in a research group especially if those folders are synchronize with a server (NAS in your case) which is automatically backed up. But, I understand your frustration to find the data and code you need from  all these different places.
So, I am wondering, could you not use your Data_Annick folder to create your own folder structure where you can either store data and code (it will mean duplication) or link the corresponding files in the other folders to your folder structure (maybe creating shortcuts)?
If you are sure that the NAS server is backed up in alignment to TU Delft ICT practices. It is fine to use that server as the storage of the master copy of data.
About the 'Theory' data. I recently met somebody from AS who was using Overleaf as the documentation tool, but also where she was collecting all the formulas for the experimental physicists. I am not familiar with the terms of use of overleaf, but if you are heavily relying on it, I would suggest to have a look at them and check the data policy. My question would be, do you know what happens if for some reason they stop the service or if there is a failure in the cloud? can they recover the data? Would it be a good idea to somehow create/download a copy time to time and save it in your folder?
As for hand written notes, I always recommend to take pictures of them or scan the notebook time to time. Having them digitize is better than having notes that can get lost :-)
Let me know if you have any questions.

**Comment by MpaulaL** [comment]
Hi @annickteepe! Thanks a lot for your assignment, it is very clear. 
I also read the issue on [folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/10#discussioncomment-5292567) and I agree with Esther's comment. I think for me is already great that you recognize that the common folders could have a better structure, and I would definitively bring your suggestions to the group. But, in any case, you could start with taking a good care and implement good practices in your folder 'Data_Annick' preparing a mini-research compendium of that folder making sure that data and code are separated, data intermediate data and final data is also separated and with good naming conventions and versioning. You can start with small steps and that is already good! 
A detailed I really liked is that you keep the files linked with the naming conventions! That is a very good practice! That the measurement code, the measurement data and the analysis code have the same name (name of the measurement) is very good. Keep doing that! You could also use tagging as a mean to keep files linked, but do not use too many, remember the recommendations for that.
I think it is also great that you are thinking a way to complete documentation with config files and creating templates for your OneNote! I really hope you do implement that!
About templates for the OnDrive, maybe you could still explore the ELNs that TU Delft offer and check what kind of template structure for the experiments they use, maybe you can get some inspiration :-) You can also make it really simple and just make sure you have the very basic est practices:

- Write down the date for each record - you that already!
- Make sure that it is possible to separate the different experiments – e.g., by using meaningful names
- Note where the raw experimental data will be stored and the name of the corresponding data file

About documentation of code, maybe you can have a look at some materials to start including in-line comments, structuring the code in functions, using docstrings for documenting the functions, etc. Here some resources that might help:

- https://gitlab.tudelft.nl/handrewsmancil/improving-coding-practices-training/
- https://coderefinery.github.io/documentation/
- https://swcarpentry.github.io/python-novice-inflammation/08-func/index.html

File formats. Remember to add the information in the ReadMe file of your project or the data/code folders that .m is MatLab files, and which version of the software you used.
Access. Since you are the only one with access to Overleaf and I also guess that it is the same case for your OneDrive notebook, remember to do a download of them time to time as back-up or for leaving them available to your group once you leave TU Deflt.

Data publication. It is OK to not have all the answers. I think it is great that your groups has the policy of publishing data and code underpinning publications! I would suggest to start implementing your plans for improving documentation while you are collecting the data and creating the code. This will save you a lot of time at the time of publishing the data and code, they will be already reusable if the documentation has been part of your research workflow. 4TU.ResearchData is a great data repository for data and code, but some of your peers are also using Zenodo. Which repository to use it should be discussed with your supervisor, the same as which data and software license to use. You can always also contact Esther for some guidance :-) Well done Annick! I hope th exercise was useful!

**Comment by EstherPlomp** [comment]
Hi @annickteepe!

Thanks for sharing your readme file! Some suggestions/comments from my side: 
- On ORCID: Toeno's ORCID is [0000-0002-6197-4808](https://orcid.org/0000-0002-6197-4808). You can set up your own identifier via that website, and use it as a place to collect all your research outputs and presentations!
- For licenses you could have prefilled it with [your preferred license from the discussion](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9#discussioncomment-5291653), but this might also change per dataset. 
- For the methodological information it is probably easier to ask a colleague/peer to have a look if this would be sufficient for them to interpret the data - that is a bit difficult to assess from my side :) 
- Not all the questions in the template will be relevant for your situation: you can also delete these information fields to keep the file shorter/more informative. 

I hope that helps for a future READme file!
