### ISSUE TITLE
Assignment 1 [Yining Zhang]

### ISSUE THREAD

**Issue by yzhang0429** [EstherPlomp/TNW-RDM-101#24]
### Introduction

Hi all, my name is Yining Zhang. I'm in my first year in Qutech. I'm working on realizing topological qubits in Kitaev chain in two dimensional electron gases.

### Reflections on the importance of RDM videos

Research data management is very important and can benefit not only reviewers but also ourselves. The 5 selfish reasons for the research data management give good explanation and example to the topic. 
My data horror story would be the recent retraction happened in Qutech about the Majorana studies. The author manipulated the data by cutting off part of it, making out the predicted feature. After being pointed out by the whistleblower, several related paper was getting retracted and there was a big impact on the whole research field.

### What would you like to learn during this course? 

I would like to learn a better way to organize and store my data. It's good to know some new ways to arrange the data, like using programming scripts or online tools.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/7)'
- [x] Assignment 2: Data Flow Map 1 (share a link in this issue before **7 March 13:00**)
https://tud365-my.sharepoint.com/:p:/r/personal/yzhang94_tudelft_nl/Documents/courses/RDM101_Assignment1_Week1_DataFlowMap_Yining.pptx?d=w339e0c622f6b4c7f8bc01a370a09a04e&csf=1&web=1&e=S3D3Tx
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/10)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Assignment 3: Data Flow Map 2 (share a link in this issue before **14 March 13:00**)
https://tud365-my.sharepoint.com/:p:/r/personal/yzhang94_tudelft_nl/Documents/courses/RDM101_Assignment2_Week2_Yining.pptx?d=wd3660b536cbc416e97471e0f5c181ac3&csf=1&web=1&e=nQfMGn
- [x] Assignment 4: Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/11)' if you have any questions (optional)
- [x] Assignment 5: Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by MpaulaL** [comment]
Hi @Yining, I am Paula, the instructor supporting Esther in this run of the course. I could not access your assignment, so I sent an access request :-). I need access to provide the feedback.

**Comment by yzhang0429** [comment]
Hello Paula,

I approved your request. Let me know if there’s still problem on access.

Best, Yining

**Comment by MpaulaL** [comment]
It works! Thanks!

**Comment by MpaulaL** [comment]
Hi Yining (@yzhang0429), thanks a lot for your assignment. I would like to share some suggestions and questions, maybe they are useful to complete the assignment even more :-)
About the data types, this is a good list! but, for the purpose of this exercise and the reflections we would like you to have, I would like to suggest that you split a bit more the list, specifically for the case of the design and fabrication data and the code.
For the design and fabrication case, you group .cad files for the design and pictures about the fabrication process. I would separate those as 'design data (or files or sketches)' which are in .cad format and the 'fabrication images' I can imagine that these images are in another format than .cad? I suggest this because later on you will need to think about how to organize these data, but also on how to document it and about file naming. I suspect that especially for documentation and file naming, the reflections will be different.
For the code, I would split the 'code for measurements' and 'code for data analysis'. I suggest this because when thinking about data organization, it might be relevant to separate those two, in different folders or by different file naming conventions, for example.
I am also missing the estimation of the data/code size. If you are not able to estimate the total size of each type of data and code, maybe you can initially indicate the size per file. This can be relevant to estimate the amount of storage you need for your project. If you work with images, these are normally big files, so it would be good to be prepared and have enough storage space .
About the storage and backup strategy. I would like that you are a bit more specific. In the video presentation you got to know different storage solutions provided by TU Delft. So, it would be great what do you mean with 'shared network drive' and 'backup network drive provided by TUD'. Are those Project Data (U:) drive? Or the Staff member (M:) drive? or OneDrive SURF drive? Or, maybe your group has set up its own shared server? If your group has its own shared server, it would be relevant also to add information about the backup strategy of that server, for example, how frequently is backed up and where and in how many places is backed up?​ 
Let me know if you have any questions.

**Comment by MpaulaL** [comment]
Hi Yining (@yzhang0429) thanks for your assignment! Only a couple of comments/feedback
The folder structure sounds fine, let me know if I understand it correctly?
Sample_X
   Device_design_and_fabrication​
      subfolder 1
       subfolder 2
   Measurement_code_and_Analysis code - I still think that maybe is a good idea to split these two
   Measurement database
Is this correct?

I think it is a good idea to keep the code and data file names linked through the chip number (I guess that is what you mean by sample?)
@annickteepe had the idea to prepare templates in OneNote in order to document the experiments in a standard manner. You can check her assignment and my comments to her.
I think you are using very good tools for documentation, OneNote as a notebook (just keep it organized!), Jupyer notebooks for the code and also having a database for the measurements.
It is interesting that the measurement code doesn't have metedata. The metadata of code could be very simple like the who created, when it was created, which version is it, the license attached to it. This tool CodeMeta generator is an example of metadata for code/software. You can use the tool to create a json file (machine readable). Maybe you or your group can use it for inspiration: https://codemeta.github.io/codemeta-generator/
Inline comments for code are good for documentation. Also think about docstrings if you are using functions in your code.
File formats. I am not sure if .CAD is an open file format. It is definitively commonly used in design. So, it would be good to add the information about the software you used for producing those .cad file in the ReadMe file of your design folder.
It is good to read that you are thinking to openly publish at least part of the measurement data. Please remember the requirements for PhD candidates about data and code publication that appear in the RDM framework policy and in the RDM policy of your faculty. So, maybe it is good to have a discussion with your supervisor and Esther to see if you can publish at least the data and code underpinning your publications.
Data publication. Please consider to publish the data (and code, if possible) in a data repository like 4TU.ResearchData or Zenodo instead of attaching it to the publication. That would make the data (and code) a bit more Findable and Accessible.
Let me know if you have any questions :-)

**Comment by yzhang0429** [comment]
Sorry for the late submission, here is my readme file:
https://tud365-my.sharepoint.com/:t:/g/personal/yzhang94_tudelft_nl/EcUZt0LPGxtPgjN6_2bpUlkBCNK_xmf5YzLDfUU4EOvzOQ?e=qIu0Z7
