### ISSUE TITLE
Assignment 1 Rosalie Wouters

### ISSUE THREAD

**Issue by rooswouters** [EstherPlomp/TNW-RDM-101#26]
### Introduction

Hi, my name is Rosalie, I am a PhD'er at Industrial Microbiology, and I love drinking tea and eating biscuits! 

### Reflections on the importance of RDM videos

It motivates me to organize my data better. Before this course it already became clear to me that I need to update my data management skills, so I am excited to get started.

### What would you like to learn during this course? 

I would like to integrate data management more in my current work flow and to have it become more streamlined. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/7)'
- [x] Assignment 2: Data Flow Map 1 (share a link in this issue before **7 March 13:00**)
https://surfdrive.surf.nl/files/index.php/s/18vRzWp4KNJ5Cxh
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/10)'
- [x] Respond to **this** GitHub issue with your readme file
https://surfdrive.surf.nl/files/index.php/s/qiYowS87HW91Ogv 
- [x] Assignment 3: Data Flow Map 2 (share a link in this issue before **14 March 13:00**)
https://surfdrive.surf.nl/files/index.php/s/C86SttL0Vb2FlmW (Only did it for 3 out of the 9 datasets, as the answers are comparable for all 9)
- [x] Assignment 4: Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/11)' if you have any questions (optional)
- [x] Assignment 5: Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Well done on assignment 2 @rooswouters! I appreciate the red flag of a collaborator, which can indeed bring in more complications to a research project 😸 With the check usage rights do you mean that this data belongs to your collaborator? Or are you reusing data? 

A note on the use of N/M drives: these are generally not recommended for the storage of research data by ICT. The [Project Drive](https://estherplomp.github.io/TNW-OS-support/posts/storage-solutions/#project-drive) is the recommended solution for research data. You can add collaborators to this drive as well. The Project drive's back ups are also more frequent!

**Comment by EstherPlomp** [comment]
Well done on assignment 3 - everything looks very clear! Fair enough that you did this assignment for 3 out of 9 datasets - no need to repeat ourselves :) 

I have a couple of pointers: 

On file formats: 
- No worries if you're not sure about file formats yet - if you ever need some advice on this you know where to find me!

On the theme of Data publication I have similar comments as also in Miriam's issue: 
- It is generally possible to share the data underlying the publication/thesis chapters. If an embargo period or restricted access is needed: 4TU.ResearchData and Zenodo allow for this (Q3). If you're working with data from industrial collaborators it may be needed to check the contractual agreements and with your supervisor which part of the data can be publicly shared. Please feel free to reach out if you need more information or a discussion about this!

**Comment by EstherPlomp** [comment]
Hi @rooswouters 

Thanks for sharing your READme file: I guess this assignment is a bit difficult to do when you don't yet have a dataset in mind where you could use it for. If you have some feedback on how to improve this - please let me know!

A couple of pointers for filling out the READme file: 
- It would be helpful to have contact information of all contributors, so probably also your PI/supervisor.
- Regarding ORCID: I just wanted to point out that this is an identifier for researchers. Similar like the identifier to the publication, it provides a way to easily identify you as a person and associate your research outputs with you. You can [set up your own ORCID](https://orcid.org/register) very easily (and use it for some scholarly platforms such as Zenodo/publishing platforms). You can have a look at [Pascale's](https://orcid.org/0000-0002-4097-7831) to see what it looks like when there is information in the profile.
- You can delete any information fields that do not seem relevant to you. If you don't have any information yet it is better to update the fields with 'to be updated' so that you don't forget about them.
