### ISSUE TITLE
Assignment 1 Maxim De Smet

### ISSUE THREAD

**Issue by MaximDeSmet** [EstherPlomp/TNW-RDM-101#27]
### Introduction

Hi, my name is Maxim and I am a PhD student at the Vandersypen Lab at QuTech, working on quantum computing with electron spins in silicon.

### Reflections on the importance of RDM videos

The main takeaway message I got from the videos was that RDM is not simply an annoying side task you are required to do for the greater good, rather it also serves for your own benefit. In the end, you will reap the rewards by securing your data, retrieving it easily, building a good reputation, saving time in many occasions, etc. 

One particular horror story that comes to mind is about hardware documentation of dilution refrigerator setups. Some files were called 'new fridge', which was totally unclear as none of our fridges are 'new' anymore and we had no clue which one it referred to. 

### What would you like to learn during this course? 

I would mainly like to learn how to implement proper data management in order to easily access data and analysis of my previous projects.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/7)'
- [x] Assignment 2: Data Flow Map 1 (share a link in this issue before **7 March 13:00**)
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/10)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Assignment 3: Data Flow Map 2 (share a link in this issue before **14 March 13:00**)
- [x] Assignment 4: Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/11)' if you have any questions (optional)
- [x] Assignment 5: Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by MaximDeSmet** [comment]
**Assignment 2: Data flow map 1**
https://surfdrive.surf.nl/files/index.php/s/pLGD2U4q5e3fLFs

**Comment by MpaulaL** [comment]
Hi Maxim (@MaximDeSmet), my name is Paula and I am the instructor supporting Esther in this run of the course. I am normally an instructor at the RDM101 course that the library provide for all faculties :-)
Thank you very much for submitting your assignment! I do have a couple of comments:
I think the list of data types is good, it is good to separate raw data from analyzed data and code. This is a very good base for when you reflect/plan your data organization. I was wondering though, you mention code or python scripts for running measurements. Do you also use Python scripts for analyzing the data (raw data -->python scripts-->analyzed data)? If yes, I would definitively add that to the list.
In the description of the different data types and code, you added information about file formats, but I am missing the information about data size. Do you have some estimates of that?
And, I am also missing the reflection on data storage and back up. I don't see it in the field allocated for that or in the other slides. Did I miss something?

**Comment by annickteepe** [comment]
Hi Maxim, 
I have looked at your data flow map. I think it is very nice that you have a separate 'metadata' category. I should definitely have this as well. I was wondering on how you do your data analysis, and how you keep track on the 'input parameter'  of you analysis code. And in what kind of folder structure do you save everything? Do you have a git repository for your code?

**Comment by MaximDeSmet** [comment]
Here's my Readme file!
[Maxim_De_Smet_Readme.txt](https://github.com/EstherPlomp/TNW-RDM-101/files/10961342/Maxim_De_Smet_Readme.txt)

**Comment by MaximDeSmet** [comment]
**Assignment 3: Data flow map 2**
https://surfdrive.surf.nl/files/index.php/s/FDYC646GaI5nf7t

**Comment by MpaulaL** [comment]
Hi (@MaximDeSmet) Maxim. Thanks for your assignment and thank you very much for integrating my comment :-)
I have some questions/comments, which I hope help:
About the data organisation. I saw your folder structure assignment and you indicate that you will implement it in the Project Data (U:) drive. You do not have a per-defined folder structure in the Staff Group (M:) drive? Wouldn't be easier to have the same folder structure in both drives? And, do you actually need to use the two drives? The (M:) drive already complies with the 3-2-1 rule, so I am wondering if you really need a (U:) drive, unless you are not allowed to organise the data as you want in the (M:). Then, I would understand that it would be practical to use the (U:) drive.
File formats. It will be relevant to add in the ReadMe file (.txt) of your project that files with the extension .oas need to be open with the KLayout software. Maybe you can even add information about the version of the software, the distributor and a link to the website.
The same as Sercan, the device design data will be restricted. Is this because you expect the commercialisation of the device. I am just asking out of curiosity :-)
Data publication. Glad to see that you would like to use 4TU.ResearchData for publishing the data. Have you considered to also publish the code? I think that publishing the code you use for analysing the data can be very valuable for others? and it can help to reproduce your results?

**Comment by EstherPlomp** [comment]
Hi @MaximDeSmet ! 
Thanks for sharing your READme file! It looks very well organised/structured - well done. Some minor suggestions: 
- If some of the information fields/questions are not relevant, you can also delete them so that the READme doesn't become cluttered. If you don't have the information right now and want to add it later you can also use a placeholder like 'to be updated'. 
- You can set up your own ORCID: https://orcid.org/register. An ORCID is similar to the identifier to the publication, it provides a way to easily identify you as a person and associate your research outputs with you. 
- You can also copy the information from the supplementary materials to your READme, so that all the relevant information is gathered in one location.
-
