### ISSUE TITLE
Assignment 1 Áron Selmeci

### ISSUE THREAD

**Issue by S-Aron** [EstherPlomp/TNW-RDM-101#44]
### Introductions
Hi all my name is Áron Selmeci and I am a PhD student in the Reactor Physics Nuclear Materials group of Faculty of Applied Sciences.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research is about investigating thermochemical and corrosion properties of salt mixtures which can be used as fuels for Generation IV Molten Salt (nuclear) Reactors. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | No  |
| Work with large data (images, simulation models) | No  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
For me the videos and presentations did not really introduce new ideas about Research Data Management. I already followed similar principles in my own work. The part about publishing is a nice ideal picture of improving the publishing process. 
My horror story connected to data handling was when I had to work on an experiment and in the same time I was expected to pay attention on what my fellow researcher explained to me, including the exact location of unlabeled samples in an oven with expecting me to carry out the experimental work properly and in the same time memorize in head what samples she was talking about and where they are. It did not work.

### What would you like to learn during this course? 
What are the views of the TU Delft about Research Data Management and how that can be implemented for drafting Research Data Management Plan.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: '[Data Flow Map](https://tud365-my.sharepoint.com/:p:/g/personal/aselmeci_tudelft_nl/EclD-6bQH2dNtTjTruilQtEBJau59h2yzRjlJJ_hCHnVxA?e=qKmIwa)'
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link: '[Revised Data Flow Map](https://tud365-my.sharepoint.com/:p:/g/personal/aselmeci_tudelft_nl/EYQAnpH158tDte-bhhRNDZMBNYeazGSGBhN6P9V3HNsFew?e=x8pOHB)'
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Hi @S-Aron! Thanks for handing in your assignment and for the helpful feedback to the assignments elsewhere!

I think you provided a nice overview in your assignment: well done! 

Some thoughts based on your assignment: 

- When working on your laptop/locally you can also make use of [OneDrive](https://estherplomp.github.io/TNW-OS-support/posts/storage-solutions/#onedrive) or [SURFdrive](https://estherplomp.github.io/TNW-OS-support/posts/storage-solutions/#surfdrive)- these also a safe storage solution for commercial/confidential data. If you want to work safer it may be better to store it in the OneDrive browser so that the files are not on your laptop should it get lost/stolen, but that may not be as user-friendly as saving it on the local drives...
- No worries about not knowing the exact file formats and sizes right now - it should still be possible to complete assignment 3 but then in less detail :)
- It will be important to consider what research outputs can eventually be shared when working with commercial/confidential data. More on that in the next assignment!

**Comment by MPolinder** [comment]
Hey @S-Aron , your flowchart looks good and clear to me. I realize it is per request of your supervisor, but I am wondering whether one should keep the master copy of the data and the modified/analyzed versions on the same drive. I think that could get messy/confusing?

**Comment by S-Aron** [comment]
> Hi @S-Aron! Thanks for handing in your assignment and for the helpful feedback to the assignments elsewhere!
> 
> I think you provided a nice overview in your assignment: well done!
> 
> Some thoughts based on your assignment:
> 
> * When working on your laptop/locally you can also make use of [OneDrive](https://estherplomp.github.io/TNW-OS-support/posts/storage-solutions/#onedrive) or [SURFdrive](https://estherplomp.github.io/TNW-OS-support/posts/storage-solutions/#surfdrive)- these also a safe storage solution for commercial/confidential data. If you want to work safer it may be better to store it in the OneDrive browser so that the files are not on your laptop should it get lost/stolen, but that may not be as user-friendly as saving it on the local drives...
> * No worries about not knowing the exact file formats and sizes right now - it should still be possible to complete assignment 3 but then in less detail :)
> * It will be important to consider what research outputs can eventually be shared when working with commercial/confidential data. More on that in the next assignment!

- As a matter of fact I already use OneDrive, just synchronizes what is on the local drive synchronizes with the cloud storage. 
- The type of the files will turn out when I will start my new experimental and simulation work. However I am sure that most of my files will not exceed 1 MB size from the measurements. Therefore in total I expect max. a couple of GBs to be used for the experimental work. Regarding the simulation work I do not know the exact size of the files, but I assume the requirement max. 100 or in worst case 200 GB. 
- Currently with the commercial a partner (more or less) monthly meetings are planned, therefore a sufficient opportunity is provided to discuss which data can be shared.

**Comment by S-Aron** [comment]
Here is my README file: https://tud365-my.sharepoint.com/:t:/g/personal/aselmeci_tudelft_nl/Ebb_-Hg4IG1NlWAgKI4RUSQBMAfNO8QWp5t0DWffGRAiQw?e=iKBzu7

**Comment by EstherPlomp** [comment]
Hi @S-Aron! Thanks for handing in Assignment 3! It looks very extensive, well done! I therefore only have a couple of small thoughts:

Data organisation
- Be careful that your file names are not getting too long. It is good to have some information in the file name, but if they get too long you'll also have to type that every time, and beyond a certain character limit the transfer of files becomes more complicated. 

Documentation
- Sometimes the simple solutions are indeed best: .txt files are not likely to break :)

File Formats
- If certain file formats are commonly used within your discipline it is of course indeed good to share data in this format. If the file sizes are not too large and it is not too much effort to also convert it to an open format, you can also consider to share the data in both file formats. I don't recommend this when the data runs into the TBs of data, because then you run into space/sustainability concerns. I have done this with some tabular data in Excel and .csv files - which I would now both use because .csv is easier to process using R - so it could potentially also be beneficial to yourself to have two copies. 

Data publication
- Sander shared the CXIDB data repository in [his issue](https://github.com/EstherPlomp/TNW-RDM-101/issues/38#issue-1693588412), which might also be of relevance to you. If you want to publish under restricted access, 4TU.ResearchData would be a better way to go.

I'll get back to you about the READme file later!

**Comment by S-Aron** [comment]
Hi @EstherPlomp, thank you for your feedback!

Data organisation
At some point I may change the filename structure (I am about a review for my data management, based on recently what type of new files I started to work with)

File Formats
I may consider to convert the files to open format as well. (Although in my research group everybody just uses the standard format provided by the measuring instrument.)

Data publication
I will consider the CXIDB and 4TU.ResearchData repository as well. In fact I plan to bring the complete DMPonline platform for a meeting with the external partner and asked them in each question what solution they would agree to.

**Comment by EstherPlomp** [comment]
Sounds great, @S-Aron, to discuss your data management plan with the collaborators! 

Regarding your READme file: 
- Great to see that you already have an ORCID!
- Regarding the citation information: here you can indicate if you want reusers to cite the dataset itself, or the accompanying publication. If you can't publish the dataset it would make more sense to refer people to the publication. 
- If there are any questions in the template that are not relevant for your research, you may also delete them. Depending on the dataset not all these questions will always be relevant. I think it is better to leave them out in this case so that your readme file becomes easier to read. 
- Great description of the methodological information: well done! Just a note that _"Calibration is strictly carried out by a technician."_ is not very informative for others to check what has been done. It could make sense here to provide the contact details of the technician if people want to learn more about the calibration methods? Or provide a brief description with some of the information of this calibration process. Additionally, this technician is then also involved in the data collection process, if only indirectly. It might be worthwhile to check with them if they want to be listed as a contributor to the dataset.

**Comment by jmvanede** [comment]
Hi @S-Aron , your READme file looks very organized and extensive! To shorten it, you might want to remove questions which are not relevant to you or answer them with "Not Applicable"/N.A..

**Comment by kgarina** [comment]
Hi @S-Aron, I like your READme file, especially the part with METHODOLOGICAL INFORMATION. I believe with this information it will be easier to reproduce the experiments if needed.
