### ISSUE TITLE
Assignment 1 Miyase Tekpinar

### ISSUE THREAD

**Issue by Miytek** [EstherPlomp/TNW-RDM-101#48]
### Introduction
Hi everyone,
I am Miyase, a PhD from bio-nanoscience departments (Applied Science). I am in my first year and I am looking for an apartment. In case I can find a pet friendly place, I WILL have two cats :D

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

I am working on fluorescence microscopy data analysis where we use different methods specifically super resolution microscopy to answer interesting biological questions. My project focuses on the utilizing AI where the theoretical way of the analysis is not sufficient or not exist to extract information we are interested in.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | Yes  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
It was eye-opening, the example cases like stolen computers or burning building. The most likely case would be that you drop computer or spilling some liquids on it accidentally. Even fixing it is possible, it will take time and in that case it would be super handy to have every thing in a server or a cloud.

### What would you like to learn during this course? 
I would like to learn the ways/options to manage my data. But many times it is not your data but it is a team work. So it is also important to agree on this with you colleagues and so everyone will store their work in a reproducible way. It would be nice to know the strategies of data management for team work or how to explain this to colleagues.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link:  https://docs.google.com/presentation/d/1MLh61qnrHwXBgdnxgDG0syGQkcdjwa3D/edit?usp=sharing&ouid=110108894326796208392&rtpof=true&sd=true
- [ ] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [ ] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link:  https://docs.google.com/presentation/d/1OCAs3lVjtf8SPjl6SFS0_bcHk0tnAmEg/edit?usp=sharing&ouid=110108894326796208392&rtpof=true&sd=true
- [ ] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Hi @Miytek! Thanks for handing in your assignment 2: well done!

- Do you have any estimations for the image formats and sizes that you'll be generating for your simulated datasets? 
- You mention 'simulated' and that you're working with code in your assignment above: Where are you storing your analysis scripts? Note that you could use GitHub for this (unless the code is commercially sensitive, which I don't think is the case since I don't see a red flag for this in your assignment), or [TU Delft's GitLab](https://gitlab.tudelft.nl/) - which is more secure but makes it more difficult to collaborate with externals. 
- I highlighted the course for image analysis using Python to others, which may also be of interest to you: '[Image Processing with Python](https://www.esciencecenter.nl/event/image-processing-with-python/)'. The eSciencecenter organises this workshop regularly if you can't make the one in June. 
- Regarding Q3: in principle if your data is on the project drive, it is already backed up at a different location by TU Delft ICT. If you want to take further precautions you can perhaps think of using OneDrive as a storage solution (up to 1 TB - pending on how large your images are). Others have mentioned in their assignment that the data repository where they want to share their data publicly also functions as a back up. More about that in the upcoming materials on FAIR, especially '[Realising FAIR: Data Publication](https://estherplomp.github.io/TNW-RDM-101/10-Realising-FAIR-Publication.html)'

Hope this helps!

**Comment by EstherPlomp** [comment]
Thanks very much for sharing your assignment 3 and for updating the public links @Miytek! It looks very clear, well done!

Documentation
- Will you use any software/programmes to collect notes on your experiments? Other people have brought up [using OneNote](https://github.com/EstherPlomp/TNW-RDM-101/issues/42#issuecomment-1556857445) and Notepad ++ for these purposes, which might be interesting to check out.  

Metadata: 
- I miss a bit of information/parameters that are important for your data collection. 

File formats: 
- I had to check if .tiff files are an open format, because I think they are - but it is not directly called 'open' anywhere. In any case, this format is very widely used and can be opened by a wide range of programmes - so it is open enough. You can still convert images to PNG - but you will use a lot of information in this conversion progress. I would only do this conversion if it helps to reduce the file sizes and not too much information is lost in the process. 

Access/Publication: 
- TU Delft expects you to share the underlying data/code of the PhD project - so unless there are any commercial/confidential restrictions on the data (which does not seem to be the case), you're expected to publicly share it using a data repository. This is indeed good to discuss with your supervisor!

**Comment by EstherPlomp** [comment]
@Miytek : I see you ticked the readme file box but I don't see a READme file shared here in your issue: do you have a link or the text available? Thanks!

**Comment by JRdeJong** [comment]
Hi! Regarding your assignment 3:
Overall seems good! I like your data organization ideas!
Regarding your simulated dataset, what does 'huge pile' mean specifically?
Does your experimental dataset needs metadata as well?

**Comment by EstherPlomp** [comment]
Hi @Miytek! Please don't forget to provide others from the course with feedback on their Assignment 2, 3 and their READme: thanks!

**Comment by moengels** [comment]
Hi Miyase, 

concerning your assignment 3, quick feedback:
- data organisation: folder organisation makes sense and filenaming for a small amount of parameters seems also reasonable, but maybe you can write log-files (plain .txt, or .yaml, .json, .mat or so) into which you write all the parameters used, so you can load your input parameters as a struct variable that you can reuse somewhere or save more than just a few parameters. 
- I can really recommend github for version control, would also help if we want to reuse code in our lab or help each other with coding issues :)

**Comment by EstherPlomp** [comment]
Thanks very much @Miytek for rounding up the assignments! 

Regarding your README: 
- This already looks very clear! I like how you explain all the contents clearly - well done!
- for licence/restrictions of reuse you can already add your preferred licence (you mentioned CC BY-NC-SA 4.0 for data in the [license thread](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34#discussioncomment-6049906)). You can always update that information later if needed.
- To link to publications I would use the DOI links: these are shorter and they do not break. So that would be https://doi.org/10.1371/journal.pone.0161602 for Girsault et al. 2016 and https://doi.org/10.1109/CVPR.2019.00223 for Krull et al. 2019 (you can just add https://doi.org/ before the numbers that start with the 10. to make it into a link if the publishers don't share the full link and just the DOI number).
