### ISSUE TITLE
Assignment 1 Robin van der Haar

### ISSUE THREAD

**Issue by RobinvanderHaar** [EstherPlomp/TNW-RDM-101#51]
### Introduction

Hi,
My name is Robin van der Haar and I am a PhD candidate at the Bioprocess Engineering group in Biotechnology since about 7 months. I am originally from the Netherlands (The Hague). My hobbies include basketball, boxing, photography, history and travelling. Nice to meet you!

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research focuses on using a technique called Raman spectroscopy as a monitoring tool to be able to characterise process parameters of bioreactors in a continuous and real-time manner. The bioreactors specifically contain co-cultures (mix of defined microbial species), as these are currently not studied and utilised as much due to the difficulty in monitoring and controlling them. As the Raman signal is measured using an in-line probe, no sample preparation is necessary either. Using the process parameters that are being collected, the cultivations could potentially be optimised by reacting to instabilities or sub-optimal conditions.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Potentially later  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes |
| Work with large data (images, simulation models) | Potentially later  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I share the fears mentioned in the videos and I want to actively safeguard my data. I am not yet sure what the best way to do this is though, which i hope to learn in this course.

### What would you like to learn during this course? 

Best practices in regards to data management mostly. Additional insights in what are the downsides of certain ways to store data.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/isTxgPqX7WSJVOQ
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link:  https://surfdrive.surf.nl/files/index.php/s/0GhE12xhA7zGC0l
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [ ] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Hi @RobinvanderHaar! Thanks for handing in assignment 2! 

It looks very detailed and comprehensive: well done! I only have a couple of thoughts/pointers:
- The combination of OneDrive/Project Drive is indeed a great one, with OneDrive being more friendly for active storage and Project Drive for backups. 
- Because I spot a .py in the data analyses part: you can also consider using GitHub/[GitLab](https://gitlab.tudelft.nl/) to manage your code/software. GitHub is better for collaboration purposes, GitLab is a more secure storage location for which you/collaborators would need a TU Delft netID. 
- Literature is indeed also a form of data! Other forms to consider are visuals/figures and your chapters/articles you'll be working on as well.

**Comment by EstherPlomp** [comment]
Thanks for sharing Assignment 3 @RobinvanderHaar! It looks very clear - well done!

just a small note on file formats: 
- Microsoft products such as PowerPoint/Word etc also need a license and are not considered an open file format (although they can be opened by open source solutions). Since these are fairy widely used this is not a huge problem, but you could consider to also share an open file format of the data such as .txt/.csv. I have shared both open and closed file format together in the past so that I preserve both the functionality of the .xlsx file, but also ensure long term preservation thanks to the .csv format of the same file. I don't necessarily recommend sharing two file formats if your data is in the TB size range - because then you run into sustainability and storage size issues. Hope this makes sense!

I'll get back to your READme file later!

**Comment by AngeliquePothuizen** [comment]
Hi @RobinvanderHaar, some feedback about your Readme file and Assignment 3. 

For the Readme file, I agree with @EstherPlomp that the readability of your file can be improved by removed all the questions / comments that are not relevant to your dataset. 

On Assignment 3, I like that you've added an indication of how big the files you are working with will be! All the included datasets / themes look like you've thought them through. However, to me it feels like some of the datasets could have been included in the different themes. For example, in the Data Organization theme you mention (Polished) Fermentation data, but I don't see any comments about this dataset in the File Format and Documentation themes. The same goes for the Raman Models dataset, this dataset is covered in the Data Organization, Metadata and File Format themes, but it is not discussed in the Access and Documentation themes while it might be relevant  to think about this? It might be obvious for you how to handle this dataset with respect to these themes, but to other people it is less obvious and for completeness it might be nice to write something (short) down.

**Comment by PabloVelazquezGarcia** [comment]
Hi @RobinvanderHaar, some more feedback for the  Assignment 3!

Very nice README file. Maybe you could have removed the non-relevant comments so that is easily readable.
I also think that it might be helpful to have a short description for the variables, so that the person that reads the README file is able to understan everything a bit more easy :)
