### ISSUE TITLE
Assignment 1 Brian Analikwu

### ISSUE THREAD

**Issue by Banalikwu** [EstherPlomp/TNW-RDM-101#53]
### Introduction
Hi! I'm Brian Analikwu and I'm a first-year PhD student in Cees Dekker's lab at Bionanoscience. I love programming, running and exercising in the gym.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research focuses on how small DNA-looping enzymes (SMC complexes: condensin, cohesin, SMC5/6) make these loops in DNA. We are particularly interested in the biophysics of this process and use fluorescence and more complex biophysics tools to study the forces, rates, kinetics that govern these enzymes.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I immediately got anxious from the thought of my laptop being stolen or my building burning down; perhaps my hard drive could go missing? However, I regularly back-up my hard drive to the TU Delft staff-bulk/groups drives and I make sure to not store anything of importance on my laptop, so no worries there. I couldn't really think of a personal horror story to be honest...

### What would you like to learn during this course? 

I would like to find out if my current practices are okay and in what way I could improve them without changing my workflow too much. I know there are plenty of tools and methods to work automate e.g. documentation and data backups.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: [Data Flow Map 1](https://surfdrive.surf.nl/files/index.php/s/G88OCWPopsgQDFl)
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link:  [Data Flow Map 2](https://1drv.ms/b/s!Audcgwy117Upg_Qw0vI1zHbX6x7E1g?e=wPZ5OF)
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [ ] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by kgarina** [comment]
Hi Brian, I really like your map. It is very organized and gives an idea not only about how you store your data, but also about how you process it!

**Comment by EstherPlomp** [comment]
Hi @Banalikwu! Thanks for handing in your assignment 2!

I could not agree more with @kgarina: well done on your assignment, it looks very clear and I can almost see you performing your workflow here!

I only have a couple of small suggestions/pointers: 
- Since you're working with images and analysing them (partly) with Python: the eScience Center organises a workshop on '[Image Processing with Python](https://www.esciencecenter.nl/event/image-processing-with-python/)' every now and then, which might be of interest to you. (You may also want to look at the assignment by @YiZhang025 who is similarly dealing with images/Python processing)
- Another mid-way in your storage solutions could be OneDrive: that location is backed up (unlike the laptop SSD) and provides you with 1 TB of space. I also saw you mention that things can be easily modified on the bulk drive: for that reason you may still want to consider using a [project drive](https://estherplomp.github.io/TNW-OS-support/posts/storage-solutions/#project-drive). Here you can determine who has access to things and/or change permissions in a more controlled manner. 

Well done! I might get back to you about using your assignment as an example, as I really like how you outlined each step of the workflow :)

**Comment by jmvanede** [comment]
Hi Brian, your data flow map is very organized and it is easy to follow how you are processing your data. Do you also already have an idea about the size per file? It might help to get an overview of the storage capacity that you need.

**Comment by Banalikwu** [comment]
Hi everyone, thank you for your input and suggestions!

@EstherPlomp I will definitely have a look at the project drive. I have seen it come across a few times before but I have looked into it only now. I really like the management of access but I will have to look into the size of the data that it can support. Right now, my raw bulk data is stored on the staff-bulk (>5TB and increasing), which means that the data currently resides on multiple directories

@jmvanede My individual image files (.tiff) are typically not that large (<2MB), but I do acquire many of them. On particularly bad days, I get more than 100GB of data. That is also why I like the staff-bulk drive, it allows storage of very very large datasets.

**Comment by Banalikwu** [comment]
My readme file:

This readme file was generated on 2023-06-01 by Brian Analikwu


GENERAL INFORMATION

Title of Dataset: Single-molecule fluorescence experiments

Author/Principal Investigator Information
Name: Cees Dekker
ORCID: 0000-0001-6273-071X
Institution: TU Delft
Address: Van der Maasweg 9, Delft, NL
Email: C.Dekker@tudelft.nl

Author/Associate or Co-investigator Information
Name: Brian T. Analikwu
ORCID: 0000-0003-0158-1989
Institution: TU Delft
Address: Van der Maasweg 9, Delft, NL
Email: B.T.Analikwu@tudelft.nl

Date of data collection: 2022-09-01 - 2023-06-31

Geographic location of data collection: Delft, Zuid-Holland, The Netherlands

Information about funding sources that supported the collection of the data: ERC 


SHARING/ACCESS INFORMATION

Licenses/restrictions placed on the data: CC-BY-NC-SA

Links to publications that cite or use the data: N/A

Links to other publicly accessible locations of the data: N/A

Links/relationships to ancillary data sets: N/A

Was data derived from another source? No


DATA & FILE OVERVIEW

File List: 
- 20221025_Rap1_yCondensin | LE Experiment with Rap1 and condensin on the R16-S6 construct
- 20221115_Rap1_yCondensin | LE Experiment with Rap1 and condensin on the R16-S6 and R16-S35 constructs
- 20230101_Rap1_yCondensin | LE and bleaching experiments with Rap1 and condensin on the R2 constructs
- 20230112_Rap1_yCondensin | Experiment with Rap1 and condensin on the R16-S10 and R16-S15 constructs


Relationship between files, if important: None, consecutive experimental days

Additional related data collected that was not included in the current data package: N/A

Are there multiple versions of the dataset? No 


METHODOLOGICAL INFORMATION

Description of methods used for collection/generation of data: HILO microscope as in Ganji et al. 2018 Science (doi:10.1126/science.aar7831). Data analysis as in Pradhan et al. 2022 Cell Rep. (doi:10.1016/j.celrep.2022.111491)

Methods for processing the data: LEADS software as in Pradhan et al. 2023, Nature (doi: 10.1038/s41586-023-05963-3)

Instrument- or software-specific information needed to interpret the data: LEADS software as in Pradhan et al. 2023, Nature (doi: 10.1038/s41586-023-05963-3)

Standards and calibration information, if appropriate: N/A 

Environmental/experimental conditions: Experiments were conducted at room temperature

Describe any quality-assurance procedures performed on the data: N/A

People involved with sample collection, processing, analysis and/or submission: B.T. Analikwu, J. van der Torre, A. Katan, C. Dekker

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @Banalikwu! It again looks great: well done!  

Documentation: 
- I like the use of Excel as a labnote book, especially since you're automating some of the calculations like this!

Data publication/access: 
Would it perhaps be possible to make part of the microscope data accessible/public? The [TU Delft/funder requirements](https://estherplomp.github.io/TNW-RDM-101/05-Essentials-for-Research-Data.html#policy-summary) are to share the processed data (data directly underlying the main conclusions/figures of articles and thesis chapters). Or does that not make any sense? Otherwise you can indeed use the 4TU.ResearchData repository to share the data under restricted access. You can share the data either on 4TU.ResearchData itself (you can make use of this for free up to 1 TB per researcher, per year!) and provide the requesters with a link, or you can provide the contact information of your PI in the public metadata. 

Regarding the project drive: in terms of storage size this is again a great solution - it will automatically scale up until 5 TB. After this you may need to get an approval of our ICT manager (André van de Berg), but as long as you use it for research data that approval will be given. Then, you can store up to 100-200 TB on a single project drive!

I'll get back about your READme file later!

**Comment by EstherPlomp** [comment]
And regarding your READme file: This looks very clear - well done! You can also consider copying the relevant methodological information from the articles you're citing (which is more important if these articles are behind a paywall - which is not the case for these). 

Another small comment would be that you can remove some of these questions that are not applicable/relevant to your dataset. Sometimes it is helpful to have confirmation that the data is not used elsewhere, but some of the N/A questions can also clutter your READme.

**Comment by dmuis** [comment]
Hi @Banalikwu your Readme file looks very clear! One comment is that in your file name you use the character "|". Note that some types of software or coding platforms do not allow such characters and it thus might be easier to use underscores or hyphens. Good luck with your project!

**Comment by jmvanede** [comment]
Hi Brian, I really like your data management plan! It is very organized and gives a good impression on how your data is processed and stored. You also reflected in a clear way on every theme, so I actually do not have anything to add.

**Comment by MPolinder** [comment]
Your second data flow map looks really nice and complete!

**Comment by lindaiqi** [comment]
Hi @Banalikwu , I have read your readme file and I do appreciate it. From your file list, it shows that you have a well-organized data sturcture. And you also provide specific links to let others learn quickly!
