### ISSUE TITLE
Assignment 1 [Nasim Heydari]

### ISSUE THREAD

**Issue by Nasimhd** [EstherPlomp/TNW-RDM-101#54]
### Introduction
 Hi, my name is Nasim Heydari. I am a PhD student in chemical engineering. I started my PhD in September 2022. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
 My research is about CO2 reduction electrolyzers integrating with renewable energy. I am working to develop a model for intermittent operating electrolyzers compatible with the energy profile from renewable sources. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | No  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | Yes |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
The videos were about why we need RDM and how it helps to avoid disaster and to provide clear data which leads to fewer mistakes. A horror story that comes to my mind is that we sometimes delete our files wrongly and later we realize that we needed the file. I think RDM helps to avoid such issues as well.

### What would you like to learn during this course? 
I would like to learn how to organize my codes in GitHub, and how to share my codes, so others can add/change the code while having the track. Also, I would like to learn how to provide the codes in GitHub for publication, as some journals ask for it.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: https://tud365-my.sharepoint.com/:f:/g/personal/nheydari_tudelft_nl/EvwPqOIFPdJGmMNJn9XODZ0BoVZhSC3XnqYatv0YhfpHFQ?e=njvJ2T
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link:  
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Hi @Nasimhd! Thanks for handing in your assignment 1! If you remove the arrow things ( --> <!-- ) when you edit your assignment you can make your answers visible. Let me know if you have any issues with that!

**Comment by EstherPlomp** [comment]
Hi @Nasimhd! I'll leave my comment for your assignment here so that you have the information in one place.

Thanks for handing in your assignment 2! It looks very comprehensive and clear: well done!

- The only thing that might be missing is file size estimations: as long as you don't go above 1 TB on your OneDrive and above 100s of TBs on the Project Drive, you should be covered :)
- OneDrive is indeed more user-friendly compared to the project drive: using the project drive as a backup location and OneDrive as your main workspace is a great approach!
- I also like that you highlighted your manuscripts/papers: these indeed also have to be safely stored. 

If you need any support navigating GitHub, please let me know!

**Comment by Nasimhd** [comment]
Hi Esther,
Actually, I am still not very familiar with GitHub, I think I shall put in some time, and see some videos to learn how it works, also for saving codes.

**Comment by Hctr95** [comment]
Hi @Nasimhd, 

Herewith are some comments about your Data Flow Map: 

* If you are working remotely and using your TUD-managed laptop, once you set your VPN connection via EduVPN. 
* Sometimes, when running long scripts and some dependencies from OneDrive you can get into the issue that the bottleneck lies on your internet connection rather than the parallelization or efficiency of your scripts.  _Just some food for thought_ ;).

**Comment by Nasimhd** [comment]
This is the ReadMe file I provide in the folder containing the models I develop:
Models.txt

-- General information:
This is to explain the two models in the project folder.

Project: dynamic modeling of the electrolyzer.
Author: Nasim Heydari
TU Delft, PPE, Chemical engineering
email: n.heydari@tudelft.nl

This project contains two models:

-----------------------Model 1 ----------------------------------

-- code information:

Lumped model contaning anode, cathode, membrane, and overvoltages.
Assumptions:
	Isothermal.
	Hydrogen evolution reaction neglected.
	inlet flowrate=50sccm
	T=40 degree C
	P=1 atm
Following parameters are studied:
	catalyst layer thickness
	CO2 inlet flowrate
	
For details of the equations refer to paper ...

---------------------Model 2 -----------------------------------


-- code information:

Dynamic model for the electrolyzer.
Assumptions:
	2 dimensional.
	Hydrogen evolution reaction neglected.
	inlet flowrate=50sccm
	T=40 degree C
	P=1 atm
Following parameters are studied:
	current density
	
	
For details of the equations refer to paper ...

**Comment by Nasimhd** [comment]
Please find my updated data flow map (assignment 3) here:

https://tud365-my.sharepoint.com/:f:/g/personal/nheydari_tudelft_nl/EvwPqOIFPdJGmMNJn9XODZ0BoVZhSC3XnqYatv0YhfpHFQ?e=VzWIhb

**Comment by EstherPlomp** [comment]
Thanks for sharing your Assignment 3 @Nasimhd! It looks very clear: well done! I only have a couple of pointers, particularly the one under 'Data publication' is relevant: 

Documentation:
I can recommend the use of notepad ++ - it has some nice visualisation options that also make superfluous spaces in code more visible. Having your code available in a different file as a back up as well can never hurt :)

Metadata: 
Is the metadata in the file names sufficient to interpret the files and their content? Do you use comments for documentation? I also saw you use readme files, so there is also additional metadata in there (code versioning etc).

File formats: 
- Python is an open source programming language, meaning that people should be able to access the Python files, although .txt files are indeed even more straightforward! I think for Python I would just stick to the Python files. 
- Word/.doc is not considered an open file format as you'll need a Microsoft license to fully interact with the file format. .txt is an alternative to .doc - but does looses some of the formatting functionality. Another format could be .md / markdown - which is what you are also using when you're interacting with GitHub. 

Data publication: 
Since I do not see any commercial flags in your data flow map, you do not have valid reasons to keep the data/code under restricted access. So you will need to have a look at how you'll share your data/code publicly underlying your articles and your thesis conclusions via a data repository. See [the third bullet point of the policy summary](https://estherplomp.github.io/TNW-RDM-101/05-Essentials-for-Research-Data.html#policy-summary) for more information. Keeping the data/code that underlie the figures and the article's conclusions as 'available upon request'  is not following the FAIR principles, which are required for PhD candidates at TU Delft. If you have any questions/concerns about this, please let me know!

**Comment by EstherPlomp** [comment]
> This is the ReadMe file I provide in one of the sub-folders, which is the folder containing the models I develop: Models.txt
> 

I think for an internal readme file this is already very clear! Maybe the enters at certain parts are a bit confusing when they address the information field on the line above it. And maybe you can include an explanation about the example folder and clarify how these examples relate to your model (folders)?

**Comment by BiffoQ** [comment]
Hi Nasim,

you have a detailed folder structure.

Cheers.
