### ISSUE TITLE
Assignment 1 Jelte de Jong

### ISSUE THREAD

**Issue by JRdeJong** [EstherPlomp/TNW-RDM-101#58]
### Introduction

Hi all, my name is Jelte de Jong. I'm a PhD candidate in the medical physics department and started last December.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

Sometimes, cancer patients needs a treatment where a part of the body is irradiated. One of the ways to do this is using proton therapy, where we irradiate the human body with protons. Before irradiation a patient-specific treatment plan needs to be made. My research focuses on improving the treatment planning part by including the probabilities for different error scenarios to occur.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | No  |
| Collaborate with industry  | Yes  |
| Write/develop software as the main output of the project  | Yes  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I never thought about reproducibility very extensively. I think that for example good documentation of your software is very useful for later, but also didn't want to spend a lot of time doing that. The video and paper convinced me of the importance of spending time doing this, as probably it will save you time later. 

### What would you like to learn during this course? 

My motivation to attend this course is to get inspiration and good practices of how to handle data/software. With the course I hope to prevent an organizational mess. I often find already that code I write I need to organize once in a while, because it gets a mess very quickly.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/lJAzf3HPVzkPVkt
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/0vRI9QD1GRPdgKJ
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [ ] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by AngeliquePothuizen** [comment]
Feedback on Assignment 2: 
It seems like you have made a nice plan to store data in several locations that are well accessible and easy to share with coworkers / collaborators if needed.

**Comment by DjanickdeJong** [comment]
Dear Jelte,

Thanks for sharing your data storage plan. I like your workflow. Especially the: Create, obtain, and use -structure seems as a logical sequence of data generation.

Also good to see you use two systems to back up your data and that you distinguish between confidential and non-confidential data.

Maybe you could clarify what format your **data** have in the simulation output? 

For the rest very clear descriptions.

Best,
Djanick

**Comment by EstherPlomp** [comment]
Hi @JRdeJong! Thanks for handing in Assignment 2: well done particularly on the data storage descriptions! Indeed, personal data needs more attention, so great flagging and remarking that this should be stored on the :u / project drive! Perhaps this comment will therefore already something you considered, but I would still like to point out that GitHub should not be used if you need to store any of the data there. For that, we have a [GitLab TU Delft instance](https://gitlab.tudelft.nl/) which is safe to use for personal/sensitive data. Any code that doesn't include the personal data can indeed be stored/managed using GitHub.

I agree with @DjanickdeJong Djanick that it would be helpful to have some more details about your data formats: This also becomes more important for the next assignment!

**Comment by JRdeJong** [comment]
ReadMe example:

This readme file was generated on 2023-05-25 by Jelte de Jong


GENERAL INFORMATION

Title of Dataset: 1D toy problem

Author/Principal Investigator Information
Name: Jelte de Jong
ORCID:
Institution: TU Delft Reactor Institute
Address: 
Email: j.r.dejong@tudelft.nl

Author/Associate or Co-investigator Information
Name: Z. Perko
ORCID:
Institution: 
Address: 
Email: 

Date of data collection: 2023-05-25

Geographic location of data collection: Delft, Netherlands

Information about funding sources that supported the collection of the data: 


SHARING/ACCESS INFORMATION

Licenses/restrictions placed on the data: 

Links to publications that cite or use the data: Unkelbach J, Paganetti H. Robust Proton Treatment Planning: Physical and Biological Optimization. Semin Radiat Oncol. 2018 Apr;28(2):88-96. doi: 10.1016/j.semradonc.2017.11.005. PMID: 29735195; PMCID: PMC5942229.

Links to other publicly accessible locations of the data: 

Links/relationships to ancillary data sets: 

Was data derived from another source?
If yes, list source(s): The code is adapted from previous versions, made by Z. Perko and J. Salverda.

Recommended citation for this dataset: 


DATA & FILE OVERVIEW

File List: 
blackboxModel.m: responsible for calculating PCE responses based on modelCase.
construct1DGeometry.m: initializing geometry of the CTV and OAR.
etc.

Relationship between files, if important: 

Additional related data collected that was not included in the current data package: 

Are there multiple versions of the dataset?
If yes, name of file(s) that was updated: 
Why was the file updated? 
When was the file updated? 


METHODOLOGICAL INFORMATION

Description of methods used for collection/generation of data:
Three cases are distinguished: discrete and continuous sampling and using PCE methods. Dose matrices are generated based on simplified 1D gaussian beamlets.

Instrument- or software-specific information needed to interpret the data: MATLAB_R2023a

Describe any quality-assurance procedures performed on the data: (probabilistic) DVH plots are determined.

DATA-SPECIFIC INFORMATION FOR: folder 1DtoyProblem

Variable List: 
CT struct, containing 
	xL, xR: left and right x coordinates of the geometry
	LX: width of geometry in x-direction
	dX: voxel width in all direction
	Etc.

**Comment by EstherPlomp** [comment]
Thanks for sharing your READme file @JRdeJong! I think it looks very clear like this, especially if additional information needed to interpret the data is available in MATLAB_R2023a.
- You can[ set up your own ORCID account](https://orcid.org/register). [0000-0002-0975-4226](https://orcid.org/0000-0002-0975-4226) gives a better impression of what it would look like once you have more research outputs. 
- While some of the contact information may appear obvious it is important to at least provide an email address to ensure that external individuals would be able to contact yourself or your supervisor if they have questions. For internal readme files this is less important. 
- Regarding the recommended citation for a dataset - if you would like people to cite the publication instead of the dataset you can make that explicit here. Or you can provide them with the citation of the dataset: it is always better to make people's lives easier here, otherwise they might not cite you in the way that you would like them to!
- Any questions in the READme file that you find less relevant can also be deleted to provide clutter. Not all the questions will always be relevant to each dataset. 

And well done on Assignment 3: it looks very clear and comprehensive!

I see you now have a closed access flag for the code. Unless there's competitive advantage involved, external collaborators or the code that your using has been developed by someone else, [TU Delft expects you to share the data and code](https://estherplomp.github.io/TNW-RDM-101/05-Essentials-for-Research-Data.html#policy-summary) that are developed during your PhD project. If Holland PTC is against the sharing of the code it is indeed a valid reason to keep the code under restricted access. 

Metadata
- For code it's also important to list software versions and any libraries/packages that your scripts are using

Data Access / Publication 
- For restricted access datasets you can still use a data repository so that access requests can be facilitated through, for example, [Zenodo](https://zenodo.org/) or [4TU.ResearchData](https://data.4tu.nl/). This may be an easier workflow if you change institutes and no longer have access to SURFdrive and/or the Project Drive for example. If you plan to use the project drive for this, it is especially important to provide contact details in your READme file so that people actually know who to contact!
- I see you highlight the patient data as open, but I would argue that this is probably closed data: Unless you have permission from Erasmus and the patients to share this data? If you mean that other individuals can request access via Erasmus it is not directly open data, as they would need to 1. request access and 2. probably fulfil some requirements to receive this access. We would call this closed/restricted data for these reasons, but it is FAIR since there is an Access procedure in place. I hope this makes sense, if not - please let me know!

**Comment by JRdeJong** [comment]
Thanks for your feedback, appreciate it!

**Comment by Hihaatje** [comment]
Hey @JRdeJong,

I just took a look at your submission for Assignment 2, I really like how in depth you went for the file naming conventions, it really strikes the balance between in depth and concise. I do have a question though, in your access theme you mention that your project is (co?) funded by a company; do you know if there is an agreement with this company for their funding? In my case this is true, and it has a lot of consequences for how I can share my research, so if this is also true for you it might be good to be aware of this.

**Comment by DjanickdeJong** [comment]
I think the readme file is clear!

For Readme File:
You could add the adress. Next to this, the building name could also be added or your department :)
Also as Esther mentioned maybe some parts could be left out in the ReadMe.
Also I know from some MATLAB that there are a lot of upgrades / toolboxes to have additional functionility in the program.
Not sure if you use any, but might be useful to include.

Thanks for sharing!

Best,
Djanick

**Comment by DjanickdeJong** [comment]
Hey Jelte,

Thanks for your PP, 

I think your naming strategy looks logical, and makes it easy to find files back. In Particular, the category 'purpose' in the naming.

For Datapublication: You could use Zenodo or 4TU.ResearchData as Esther mentioned. I was not sure if it would be applicable to you, as you mentioned you work with both confidential data and other stakeholders.

@EstherPlomp; Thanks for this information: 'or restricted access datasets you can still use a data repository so that access requests can be facilitated through'. did not know this!

Best,
Djanick
