### ISSUE TITLE
Assignment 1 Angelique Pothuizen 

### ISSUE THREAD

**Issue by AngeliquePothuizen** [EstherPlomp/TNW-RDM-101#60]
### Introduction
Hi! My name is Angelique Pothuizen. I am a first year PhD student working the in the Biocatalysis group in the department of Biotechnology. I am 25 years old and I live in the city center of Delft. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research focusses on improving enzymes more suitable for industrial application through protein engineering and kinetic analysis. The goal is to use those improved enzymes to replace classical chemical production processes and make production of certain (bio)chemicals more sustainable. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | No  |
| Work with large data (images, simulation models) | No  |
| Other:  | N/A  |

### Reflections on the importance of RDM videos

I think the 'Why RDM is relevant for you' video comes with clear argumentation why RDM is important. The Markowetz paper / video also shows in a clear way what can go wrong if you do not take sufficient care of your research data while also showing the benefits of proper RDM. 

### What would you like to learn during this course? 

I would like to improve / incorporate a little more structure in my data and become more aware of how to handle data. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: [DataFlowMap-AP](https://surfdrive.surf.nl/files/index.php/s/7BaBM0ZHbCiCo96)
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link:  [DataFlowMap2-AP](https://surfdrive.surf.nl/files/index.php/s/L5jVihXvuN2gp0X)
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by AngeliquePothuizen** [comment]
[AngeliquePothuizen_ProteinFusion_Readme.txt](https://github.com/EstherPlomp/TNW-RDM-101/files/11489200/AngeliquePothuizen_ProteinFusion_Readme.txt)

**Comment by EstherPlomp** [comment]
Hi @AngeliquePothuizen! Thanks for handing in your assignments! 

Regarding Assignment 2 I have very little feedback since this looks super comprehensive! Well done!
- Another thing to consider is whether you maybe have analysis protocols, literature, thesis chapters or articles that you need to store somewhere. 
- Your backup strategy looks solid! If you want to make use of storage solutions that are a bit more user friendly, you could look into SURF/Onedrive.

**Comment by Hctr95** [comment]
> [AngeliquePothuizen_ProteinFusion_Readme.txt](https://github.com/EstherPlomp/TNW-RDM-101/files/11489200/AngeliquePothuizen_ProteinFusion_Readme.txt)

Hi @AngeliquePothuizen, 

Your Readme.txt file looks great! I want to point out some details that I consider might be useful to add: 

* I would add the folder structure for the project in addition to the list that you provided, without such structure it might be difficult to grasp how the files are related to each other and get an idea of the pipeline.  @EstherPlomp, do you know by any chance if you can automatically create the folder structure and add it to this file? It would be handy when developing newer versions and having everything up to date. 
* When checking the Data and File Overview section, Introducing some tabs between the names of the files and their description might be more user-friendly.

Keep it up!

**Comment by Hctr95** [comment]
Hi @AngeliquePothuizen, 

I am curious about the metadata from the Chromatogram software (Labsolutions). Do you also get the details about the column, eluent, and conditions under which the analyses were carried out by default from the .png and .xlsx files? Can you also export the .xlsx file as .csv to make it more accessible? I recall once I had to process some chromatograms and some details were missing, I had to contact the technician to get the details about the protocol and technical specs used for my samples. 

Apart from that, it looks like a solid plan! You seemed to have thought about most of the details. Keep it up! 

Best,

**Comment by EstherPlomp** [comment]
Thanks for sharing your readme file and Assignment 3 @AngeliquePothuizen! I hope you had a lovely holiday in the meantime!

And apologies for not responding to your question about the automatic folder structure reporting @Hctr95! I'm not aware of existing tools, but asked some colleagues if they may know more. I'll get back to you about this if I hear more!

 Regarding your READme file: 
- Very clear overview: well done!
- There are 'restrictions' on the data if you choose the CC BY-SA licence that you indicated in [your license preference](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34#discussioncomment-5914618). The restriction would be that people should cite the original work and if they redistribute it that they do this under the same license. While this is a very limited restriction, it is still a restriction technically! It suffices to just list the license here.
- You can also [set up your own ORCID account](https://orcid.org/register)! This becomes more relevant further in your career, when you'll have more research outputs. 

And some feedback on Assignment 3: Well done! It looks very clear and comprehensive!

Documentation/Metadata
- You mention that no documentation and metadata is needed for the images: Is that because the documentation is automatically collected? Or is there really no documentation needed to interpret the files because it is always clear why and how the images are generated and what they contain? 

File format
- Fair point that some of your data may not be functional in an open format if you need a particular software to process it! For some cases it may still be worthwhile to convert files to open file formats when you share them publicly. If no relevant information can be shared in an open file format, I would argue that you can leave it in the original file format. Sometimes it is worthwhile to share data in open formats because it facilitates preservation and these file formats are more likely to be openable in 15 years - but if you can then not do anything with them we might have lost the point :). 
- Also a small note that .xls is a proprietary format and .csv is the open alternative to it (since you still need a microsoft license to interact fully with the format). Because it can be opened by other programmes and it is a commonly used format it is less problematic, but in some cases you may still want to convert and share data in a .csv format and/or share both file formats so that you have both the usability and preservation boxes ticked. (Don't do this with massive files that take up a lot of space, because then you run into storage and sustainability issues :))

**Comment by AngeliquePothuizen** [comment]
Thanks you for your feedback @Hctr95 and @EstherPlomp!
 
@Hctr95, about the metadata from Labsolutions, I looked a little into export options in the software and it looks like individual files can be exported in a plain text (ASCI) - format. However, exporting chromatograms to a plain text format does not really feel useful since I think it results in a loss of the direct visual component. However, if you feel different I am open to discuss this of course!
The .XLS file I mentioned in my assignment is a manually created file containing the .PNG chromatograms, so this is not a direct export from the Labsolutions program itself. In most cases, the chromatogram itself does show the used temperature gradient (in case of GC analysis) or solvent gradient (in case of HPLC analysis). However, it is quite difficult to extract this from the chromatogram on its own so additional information about the used method is required to replicate the results. In a publication this will of course be present in the M&M section, but an additional Readtime.txt file in the uploaded dataset with this information would help with the data being FAIR and I will keep this in mind! 

@EstherPlomp, considering the image metadata, giving this a second thought (with a fresh after holiday mind) this type of data might benefit from a Readme.txt file as well. Usually, the pictures are easy to interpret but you do need additional information to know what exactly you are looking at. Normally, this information is present in the M&M section of a publication and / or description of the figure, but I see how an additional explanatory file uploaded with the images itself might help with the FAIR principle. 
And thanks for the .xls / .csv format comment, a very fair point indeed!

**Comment by EstherPlomp** [comment]
Thanks for your reply @AngeliquePothuizen! If things don't make sense and result in too much loss of information please do leave things as it is. I'm happy to see the discussion about this going, so thanks @Hctr95 for bringing this up!

And a colleague of mine responded with a solution to **share folder structures**! You do need some command line experience to manage though: 
>
> exporting the output of the tree command might be all you need. Should be available on many Operating Systems. See examples for Linux: https://www.geeksforgeeks.org/tree-command-unixlinux/
> 

I haven't tried this myself yet - but if I manage to get it working I'll update the materials to give people this option for the sharing of their folder structures. So thanks @Hctr95 for bringing this up as well!

**Comment by AngeliquePothuizen** [comment]
Hi @EstherPlomp, I have given feedback to Robin van der Haar his assignment and readme file. Feedback was posted 5 days ago, please let me know if you can't find it!

**Comment by EstherPlomp** [comment]
Excellent, thanks @AngeliquePothuizen! For some reason I totally overlooked this, apologies! You're all complete in that case!

**Comment by BiffoQ** [comment]
Hi @AngeliquePothuizen,

nice job with the 3rd assignment.

I think you did not include a file naming convention in your folder structure.

Cheers.
