### ISSUE TITLE
Assignment 1 Pablo Velazquez

### ISSUE THREAD

**Issue by PabloVelazquezGarcia** [EstherPlomp/TNW-RDM-101#63]
### Introduction

Hi there! I am Pablo Velazquez and I am a PhD candidate in the biotechnology department and in the biocatalysis group. I Love sports and cooking :D
### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research focuses on the design and testing of new enzymes with potential applications in chemical and pharmaceutical processes. Using protein engineering tools, we aim for a new and greener and more sustainable chemistry.
### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | /No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes/  |
| Collaborate with industry  | Yes/  |
| Write/develop software as the main output of the project  | /No  |
| Use code (as in programming) for data analysis | /No  |
| Work with large data (images, simulation models) | Yes/  |

### What would you like to learn during this course? 

I would like to learn how to manage different kinds of data, in different formats in a easy and intuitive way.
### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: 
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link:  
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by PabloVelazquezGarcia** [comment]
Assignement 2

https://surfdrive.surf.nl/files/index.php/f/13024904754

**Comment by PabloVelazquezGarcia** [comment]
Assignement 3

https://surfdrive.surf.nl/files/index.php/apps/files/?dir=/&view=sharinglinks

**Comment by EstherPlomp** [comment]
Thanks for sharing part of your assignment 3 @PabloVelazquezGarcia! I can't access the files you shared via SURFdrive - can you check again whether you have set up a public link to share the files? (See [here for the steps you'll need to take](https://estherplomp.github.io/TNW-OS-support/posts/data-sharing-SURFdrive/)). The same comment still applies to your assignment 2 as well. Please let me know if we need to set up a quick call with some screensharing to get this sorted! 

Regarding your comment on open files: word/excel files are not an open format because you'll need a microsoft license to fully interact with these file types. Alternatives would be .txt or .md files for word, or .csv for Excel! 

And good to see you're already documenting everything via (electronic) lab notes!

**Comment by EstherPlomp** [comment]
And the feedback! Hope it is helpful: 

Assignment 2: 
- Please be careful with storing data on USBs; they are easily lost and corrupted and should only be used to transfer files, not as a storage solution. 
- What do you mean with TU Delft.net? Is this one of the network drives? 
- Do you also have analysis protocols? Figures/images you'll have to work with? 

README: 
- For the title of the dataset it is good to be a bit more descriptive. This can be difficult now if you don't have a particular dataset to share yet, but for example: dataset underlying the article "title article" or another title that describes the dataset itself a bit more. 
- Please do add the last names of contributors to the datasets that you plan to share externally: otherwise it will be difficult to find/contact individuals. With the ORCID you can identify researchers more easily. You can set up your own ORCID here: https://orcid.org/register
- For the licenses/restrictions you can indicate the license for the data that you have to share in the [license thread](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34). 
- For the recommended citation I would list out the full contributor list, and then also the title of the dataset. This is similar to a regular publication reference and should here be written out fully. 
- When technicians and students are involved in the research project, you can ask them if they want to be listed as a contributor on the dataset with their contact details
- Please be sparing with the use of caps in your README. All caps text is not accessible for screen readers and it can be more difficult to read generally
- For the quality procedures/calibration curves: it would be helpful to describe this in a bit more detail. You can compare the methodological information in the readme file to the methods section in an article. It can be worthwhile to copy past some of the text in your future article to the readme file of your future dataset :)
- And lastly; If any of the questions are unhelpful or not relevant to a particular dataset, you can also delete them. This also helps with the readability of your READme.
