### ISSUE TITLE
Assignment 2 - Data Flow Map Ziqing Yuan

### ISSUE THREAD

**Issue by ZQYZQYZQ** [EstherPlomp/TNW-RDM-101#94]
[Assignment 2 - Data Flow Map Ziqing Yuan.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/12665239/Assignment.2.-.Data.Flow.Map.Ziqing.Yuan.pptx)
Hi everyone, Here I share my Data flow map with you. Feel free to leave any comments on it. Thank you!

**Comment by EstherPlomp** [comment]
Hi @ZQYZQYZQ!

Thanks for sharing assignment 2!  

Could you please still complete [assignment 1 ](https://estherplomp.github.io/TNW-RDM-101/03-Assignment-GitHub-1.html) and open up an overview issue so that we can share your assignment there? You can see the other issues in the repository as an example. 

Please let me know if you have issues completing this: happy to help!

**Comment by EstherPlomp** [comment]
I'll place the feedback on assignment 2 here for now: It looks very clear and comprehensive, well done @ZQYZQYZQ !

Some feedback and questions that I have:
- Why do you need to check the usage rights of the raw optical data? Will you not generate this yourself? 
- I like how you included your literature database as a dataset! That is indeed also a form of data. Another form could be the images that you use in publications, or the article/chapter texts themselves!
- I do not see file sizes and formats in your assignments, so I hope you don't run into any storage space issues. OneDrive stores data up to 1 TB, but the Project Drive should be able to handle more :). File formats will play a more important role in assignment 3. 
- Do you have any notes or other form of documentation that could be its own separate dataset?
