### ISSUE TITLE
Assignment 2 Giacomo Lastrucci

### ISSUE THREAD

**Issue by giacomolastrucci** [EstherPlomp/TNW-RDM-101#97]
Hello everyone, 
please, find [here](https://surfdrive.surf.nl/files/index.php/s/gvMlqnpZbDopXQr) my data flowmap. 
Feel free to leave any comments or feedback.
Thank you!

Best,
Giacomo

**Comment by PJL-vandenberg** [comment]
Hey Giacomo,

Looks good! I like the division between the confidential data and the open data. Including training sets that can be public seems like a great idea for transparency. The only question I have is: "What are your plans for code documentation, to prevent bits of code that make sense to you when documented in your way, but might not to your successor?" Because it has happened to me before that somebody handed me 50 lines of code commented with "This makes the dataset from the model data", because the steps made sense to him.

**Comment by EstherPlomp** [comment]
Hi @giacomolastrucci and @PJL-vandenberg ! Thanks for sharing assignment 2 and for already providing feedback! To keep better track of all the assignments and feedback I'll move this information to the original issue by @giacomolastrucci #83.
